### ISSUE TITLE
Твой плейбук гавно

### ISSUE THREAD

**Issue by Nesquk** [kounne/ansible_expo#1]
Привет, плейбук не работает( Посмотри пожалуйста до завтра(17:00)

**Comment by kounne** [comment]
Сам ты говно, у меня на машине работает

**Comment by Nesquk** [comment]
![18e4eb75fdaa3e66bbfdf02473449cb3_3759409955038975496](https://github.com/user-attachments/assets/0081e499-8737-424c-bf00-4ef691d5716b)
